# ============================================================
# CHINAWOK BACKEND - SERVERLESS COMPOSE
# ============================================================
# Este archivo orquesta el despliegue de todos los microservicios
# del backend de ChinaWok usando Serverless Framework Compose
# ============================================================

# Instrucciones de uso:
# 1. Configura tu archivo .env basándote en .env.example
# 2. Asegúrate de tener credenciales AWS configuradas en ~/.aws/credentials
# 3. Ejecuta: serverless deploy (despliega todos los servicios)
# 4. O despliega servicios individuales: serverless deploy --service=usuarios

services:
  # ------------------------------------------------------------
  # LAMBDA LAYER: DEPENDENCIAS COMPARTIDAS
  # ------------------------------------------------------------
  # Layer con todas las dependencias Python comunes
  shared-layer:
    path: Layers
    params:
      default:
        org: ${env:SERVERLESS_ORG, 'flanche'}

  # ------------------------------------------------------------
  # MICROSERVICIO: USUARIOS
  # ------------------------------------------------------------
  # Gestión de usuarios, autenticación y autorización
  usuarios:
    path: Microservicios/Usuarios
    dependsOn:
      - shared-layer
    params:
      default:
        org: ${env:SERVERLESS_ORG, 'flanche'}

  # ------------------------------------------------------------
  # MICROSERVICIO: LOCALES
  # ------------------------------------------------------------
  # Gestión de locales/restaurantes
  locales:
    path: Microservicios/Locales
    dependsOn:
      - shared-layer
      - usuarios
    params:
      default:
        org: ${env:SERVERLESS_ORG, 'flanche'}

  # ------------------------------------------------------------
  # MICROSERVICIO: EMPLEADOS
  # ------------------------------------------------------------
  # Gestión de empleados y reseñas
  empleados:
    path: Microservicios/Empleados
    dependsOn:
      - shared-layer
      - locales
    params:
      default:
        org: ${env:SERVERLESS_ORG, 'flanche'}

  # ------------------------------------------------------------
  # MICROSERVICIO: PEDIDOS
  # ------------------------------------------------------------
  # Gestión de pedidos, productos, combos y ofertas
  pedidos:
    path: Microservicios/Pedidos
    dependsOn:
      - shared-layer
      - locales
      - usuarios
    params:
      default:
        org: ${env:SERVERLESS_ORG, 'flanche'}

  # ------------------------------------------------------------
  # MICROSERVICIO: STEP FUNCTIONS (WORKFLOW)
  # ------------------------------------------------------------
  # Orquestación del flujo de pedidos
  stepfunctions:
    path: Microservicios/Stepfunctions
    dependsOn:
      - shared-layer
      - pedidos
      - empleados
    params:
      default:
        org: ${env:SERVERLESS_ORG, 'flanche'}

# ------------------------------------------------------------
# VARIABLES COMPARTIDAS
# ------------------------------------------------------------
# Estas variables están disponibles para todos los servicios
params:
  default:
    region: ${env:AWS_REGION, 'us-east-1'}
    org: ${env:SERVERLESS_ORG, 'flanche'}
