# ============================================================
# CHINAWOK BACKEND - SERVERLESS COMPOSE
# ============================================================
# Este archivo orquesta el despliegue de todos los microservicios
# del backend de ChinaWok usando Serverless Framework Compose
# ============================================================

# Instrucciones de uso:
# 1. Configura tu archivo .env basándote en .env.example
# 2. Asegúrate de tener credenciales AWS configuradas en ~/.aws/credentials
# 3. Ejecuta: serverless deploy (despliega todos los servicios)
# 4. O despliega servicios individuales: serverless deploy --service=usuarios

org: flanche
app: chinawok-backend
stage: dev

services:
  shared-layer:
    path: Layers

  usuarios:
    path: Microservicios/Usuarios
    dependsOn:
      - shared-layer

  locales:
    path: Microservicios/Locales
    dependsOn:
      - shared-layer
      - usuarios

  empleados:
    path: Microservicios/Empleados
    dependsOn:
      - shared-layer
      - locales

  pedidos:
    path: Microservicios/Pedidos
    dependsOn:
      - shared-layer
      - locales
      - usuarios

  stepfunctions:
    path: Microservicios/Stepfunctions
    dependsOn:
      - shared-layer
      - pedidos
      - empleados

